### PR TITLE
restrict to only drupal/* packages

### PR DESCRIPTION
**Pull request by tedbow**
An idea to get around https://github.com/composer/composer/issues/11704 for testing purposes. 

@phenaproxima  is trying to solve the memory issue in https://github.com/php-tuf/composer-integration/pull/91
While this is not permanent solution, it might be something to try to make sure this is not causing additional problems

### CODE REVIEW

**Comment by tedbow** [comment]
I tried setting `only` on a local project and it does seem to solve the problem of seeing these
`Downloading https://packages.drupal.org/files/packages/8/p2/egulias/email-validator.json`

It actually cut the number of instances in verbose output of `Downloading https://packages.drupal.org/files/packages/8/p2` from 65 to 7. So it seems without this all packages are being looked for on `packages.drupal.org`. So I wonder if this will actually help some of the memory issues.

**Comment by tedbow** [comment]
It also cuts the 404s to 4 from 61. The remaining for 404s are 
```
[404] https://packages.drupal.org/files/packages/8/p2/drupal/core-project-message.json
[404] https://packages.drupal.org/files/packages/8/p2/drupal/core-composer-scaffold.json
[404] https://packages.drupal.org/files/packages/8/p2/drupal/core-recommended.json
```
Which are reasonable since these match `drupal/*` but aren't hosted there.
But also 
`[404] https://repo.packagist.org/p2/drupal/token.json`

which is strange because it was already successfully downloaded from packages.drupal.org

**Review by phenaproxima — APPROVED** [review]

**Comment by phenaproxima** [comment]
I had to revert this guy. It turns out that, with this change, running something like `drupal require -vvv drupal/diff` will bypass TUF protection. You'll see lines in the output like `TUF integration enabled`, suggesting that the _plugin_ is enabled...but you won't see any lines prefixed with `[TUF]`, which are output by the plugin as it does its work.

**Comment by phenaproxima** [comment]
The problem here is due to what Composer's `RepositoryManager` does when it encounters an `only` config option: it creates a `FilterRepository` decorator around the `ComposerRepository`. That's problematic for us -- the plugin doesn't account for this.

**Pull request merged**
